apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - __PRODUCTION_BASE_KUSTOMIZE_PATH__
patches:
  - path: ingress-production.patch.yaml
  - path: networkpolicy-production-egress.patch.yaml
images:
  - name: ghcr.io/lu149e/system
    newName: ghcr.io/lu149e/system
    digest: __PRODUCTION_IMAGE_DIGEST__
