apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-api
spec:
  rules:
    - host: auth-staging.example.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-api
                port:
                  name: http
  tls:
    - hosts:
        - auth-staging.example.internal
      secretName: auth-staging-tls
